apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-girus
  namespace: sensacional-juvenal
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-girus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-girus
    spec:
      containers:
      - name: nginx-girus
        image: nginx:1.16.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
          requests:
            memory: "64Mi"
            cpu: "100m"


