apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-system
  namespace: metallb-system
spec:
  addresses:
  - 192.168.100.252-192.168.100.254

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-system
  namespace: metallb-system
spec:
  ipAddressPools:
  - metallb-system
