apiVersion: v1
kind: Pod
metadata:
  name: home
  labels:
    name: home
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /home/william/tmp
      name: primeiro-emptydir
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
         cpu: "0.1"
         memory: "64Mi"
    ports:
      - containerPort: 80
  volumes: 
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: "256Mi"
