apiVersion: v1
kind: Pod
metadata:
  name: home
  labels:
    run: home
    service: webserver
spec:
  containers:
  - name: nginx
    image: nginx
    resources: {}
  - name: alpine
    image: alpine
    args: 
    - sleep 
    - "100"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
