apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotten-potatoes
spec:
  selector:
    matchLabels:
      app: rotten-potatoes
  template:
    metadata:
      labels:
        app: rotten-potatoes
    spec:
      containers:
      - name: rotten-potatoes
        image: willmuller/rotten-potatoes:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: dockerhub-secret


