Vagrant.configure("2") do |config|
    (1..1).each do |i|
        config.vm.define "master-#{i}" do |k8s|
            k8s.vm.box = "eurolinux-vagrant/oracle-linux-8"
            k8s.vm.hostname = "master-#{i}"
            k8s.vm.network "public_network", ip: "192.168.122.201", bridge: "wlp3s0"

            k8s.ssh.insert_key = false
            k8s.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
            k8s.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
            
            k8s.vm.provision "shell", inline: File.read("install_docker.sh")

            k8s.vm.provider "virtualbox" do |vb|
              vb.gui = false
              vb.cpus = 3
              vb.memory = "4096"

            end
        end
    end

#   (1..1).each do |i|
#        config.vm.define "worker-#{i}" do |k8s|
#            k8s.vm.box = "eurolinux-vagrant/oracle-linux-8"
#            k8s.vm.hostname = "worker-#{i}"
#           k8s.vm.network "public_network", ip: "192.168.122.202", bridge: "wlp3s0"

#            k8s.ssh.insert_key = false
#            k8s.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
#            k8s.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

#            k8s.vm.provision "shell", inline: File.read("install_docker.sh")

#            k8s.vm.provider "virtualbox" do |vb|
#              vb.gui = false
#              vb.cpus = 2
#              vb.memory = "2048"
#            end
#        end
#    end
end
