Vagrant.configure("2") do |config|
  (1..1).each do |i|
    config.vm.define "worker-#{i}" do |k8s|
      k8s.vm.box = "ubuntu/focal64"
      k8s.vm.hostname = "worker-#{i}"
      k8s.vm.network "public_network", ip: "192.168.100.201", bridge: "wlp3s0"
      k8s.vm.network "public_network", ip: "192.168.100.201", bridge: "enx207bd2c4383b" 

      k8s.ssh.insert_key = false
      k8s.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
      k8s.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

      k8s.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.cpus = 4
        vb.memory = "4096"
      end
    end
  end
end



#curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET sh -s - server --cluster-init --node-ip=10.147.18.185
#curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --flannel-backend=host-gw --tls-san=192.168.100.200 --bind-address=192.168.100.200 --advertise-address=192.168.100.200 --node-ip=192.168.100.200 --cluster-init" sh -s -
#sudo cat /var/lib/rancher/k3s/server/node-token
#curl -sfL https://get.k3s.io | K3S_TOKEN=SECRET sh -s - agent --server https://10.147.18.185:6443 --node-ip=10.147.18.2

