Vagrant.configure("2") do |config|
  (2..2).each do |i|
      config.vm.define "server-#{i}" do |k8s|
          k8s.vm.box = "ubuntu/focal64"
          k8s.vm.hostname = "master-#{i}"
          k8s.vm.network "public_network", ip: "192.168.100.200", bridge: "enx207bd2c4383b"

          k8s.ssh.insert_key = false
          k8s.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
          k8s.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
          
          k8s.vm.provision "shell", inline: File.read("install_docker.sh")

          k8s.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.cpus = 2
            vb.memory = "2048"

          end
      end
  end
end