apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: nfs
  name: pv-argocd-nfs
  namespace: argocd
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.100.254
    path: "/mnt/nfs"
  storageClassName: nfs
