apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: pvc-nfs-redis
  name: pvc-nfs-redis
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs
  selector:
    matchLabels:
      storage: nfs
