apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: pvc-argocd-nfs
  name: pvc-argocd-nfs
  namespace: argocd
spec:
  resources:
    requests:
      storage: 15Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs
  selector:
    matchLabels:
      storage: nfs
