apiVersion: v1
kind: Secret
metadata:
  name: argocd-github-secret
  namespace: argocd
stringData:
  token: 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

---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  sourceRepos:
  - 'https://github.com/willmiiller/DescomplicandoKubernetes'

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: DecomplicandoKuberntes
spec:
  project: default
  source:
    repoURL: 'https://github.com/willmiiller/DescomplicandoKubernetes'
    targetRevision: HEAD
    path: Deploy-automatico
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - Validate=false
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true




