apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: giropops-senhas-tls
spec:
  secretName: giropops-senhas-tls # Nome do segredo desejado
  dnsNames:
  - giropops-senhas.williamuller.io
  issuerRef:
    name: letsencrypt-prod # Nome do seu emissor de certificado
    kind: ClusterIssuer
