apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;
        listen 443 ssl;

        ssl_certificate /etc/nginx/tls/nginx.crt;
        ssl_certificate_key /etc/nginx/tls/nginx.key;

        location / {
           return 200 'Ola LinuxTips!\n';
           add_header Content-Type text/plan;
        }
      }
    }

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-https
  labels:
    app: nginx-https
spec:
  containers:
  - name: nginx-https
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    - containerPort: 443
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
    - name: nginx-tls
      mountPath: /etc/nginx/tls
  volumes:
  - name: nginx-config
    configMap:
      name: nginx-config
  - name: nginx-tls
    secret:
      secretName: nginx-secret
      items:
      - key: tls.crt
        path: nginx.crt
      - key: tls.key
        path: nginx.key

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-https
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 32400
  type: NodePort


