

apiVersion: v1
kind: Pod
metadata:
  name: nginx-https
  labels:
    name: nginx-https
spec:
  containers:
  - name: myapp
    image: nginx-https
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    - containerPort: 443
      volumeMounts:
      - name: nginx-config
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
      - name: nginx-tls
        mountPath: /etc/nginx/tls
    volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
    - name: nginx-tls
      secret:
        secretName: williamuller.io
        items:
        - key: tls.crt
          path: certificado.crt
        - key: tls.key
          path: chave-privada.key

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: myapp
  ports:
  - port: <Port>
    targetPort: <Target Port>

